import React, { useContext } from "react";
import { useRegion } from "../RegionContext";
import { TrendingUp, TrendingDown, Activity, Percent, Crosshair, BarChart2, Download } from 'lucide-react';
import html2pdf from 'html2pdf.js';

function fmt(n, suffix = "") {
  if (n === null || n === undefined) return "—";
  return `${Number(n).toLocaleString(undefined, { maximumFractionDigits: 2 })}${suffix}`;
}

function StatCard({
  label,
  value,
  subtext = null,
  highlight = false,
  negative = false,
  icon: Icon
}) {
  return (
    <div
      className={`p-5 rounded-xl border transition-all hover:-translate-y-1 hover:shadow-md ${highlight ? "bg-indigo-50 dark:bg-indigo-500/20 border-indigo-100 dark:border-indigo-500/30 " : "bg-white dark:bg-zinc-900 border-slate-200 dark:border-zinc-800 "} shadow-sm flex flex-col`}
    >
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs font-semibold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">
          {label}
        </span>
        {Icon && <Icon className={`w-4 h-4 ${highlight ? 'text-indigo-500' : 'text-slate-400 dark:text-zinc-500'}`} />}
      </div>
      <div className="flex items-baseline gap-2">
        <span
          className={`text-2xl font-bold tracking-tight ${negative ? "text-red-600 dark:text-red-400" : "text-slate-900 dark:text-zinc-50 "}`}
        >
          {value}
        </span>
      </div>
      {subtext && (
        <span className="text-xs font-medium text-slate-400 dark:text-zinc-500 mt-1">{subtext}</span>
      )}
    </div>
  );
}
export default function ResultsTable({ results }) {
  const { region } = useRegion();

  const handleDownloadReport = () => {
    if (!results) return;
    const { summary, risk_metrics: risk, trade_statistics: trades, ticker, start_date, end_date, strategy } = results;

    // Grab the ECharts canvas to include as an image
    const canvas = document.querySelector('canvas');
    let chartImageHTML = '';
    if (canvas) {
      const dataUrl = canvas.toDataURL('image/png');
      chartImageHTML = `<div style="margin-top: 20px; text-align: center;"><img src="${dataUrl}" style="max-width: 100%; height: auto; border: 1px solid #ccc; border-radius: 8px;" /></div>`;
    }

    const htmlContent = `
      <div style="font-family: Arial, sans-serif; padding: 30px; color: #333; line-height: 1.6;">
        <h1 style="color: #4f46e5; text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">Chronos Backtest Report</h1>
        
        <p style="font-size: 14px;">
          This report provides a detailed, plain-text summary of the historical backtest simulation for <strong>${ticker}</strong>. 
          The simulation tested the <strong>${strategy}</strong> strategy over the time period from <strong>${start_date}</strong> to <strong>${end_date}</strong>.
        </p>

        <h3 style="color: #1e293b; margin-top: 20px;">1. Investment Overview</h3>
        <p style="font-size: 14px;">
          Starting with an initial capital of <strong>${region.currency}${fmt(summary.initial_capital)}</strong>, the portfolio reached a final value of <strong>${region.currency}${fmt(summary.final_value)}</strong>. 
          This represents a total overall return of <strong>${fmt(summary.total_return_percent, "%")}</strong> over the entire period, which breaks down to an annualized return of <strong>${fmt(summary.annualized_return_percent, "%")}</strong> per year.
        </p>

        <h3 style="color: #1e293b; margin-top: 20px;">2. Risk and Volatility</h3>
        <p style="font-size: 14px;">
          During this period, the strategy experienced a maximum drawdown (the largest peak-to-trough drop) of <strong>${fmt(risk.max_drawdown_percent, "%")}</strong>. 
          The Sharpe Ratio, which measures risk-adjusted return, stands at <strong>${fmt(risk.sharpe_ratio)}</strong>. A higher Sharpe Ratio generally indicates that the returns are being generated without taking on excessive risk.
        </p>

        <h3 style="color: #1e293b; margin-top: 20px;">3. Trade Performance & Benchmark</h3>
        <p style="font-size: 14px;">
          The system executed a total of <strong>${trades.total_trades}</strong> trades, out of which it was profitable <strong>${fmt(trades.win_rate_percent, "%")}</strong> of the time. 
          In comparison, simply buying and holding the asset would have resulted in a benchmark return of <strong>${fmt(summary.benchmark_return_percent, "%")}</strong>. 
          Ultimately, this strategy performed <strong>${fmt(summary.strategy_vs_benchmark, "%")}</strong> relative to the buy-and-hold benchmark.
        </p>

        ${chartImageHTML}
        
        <div style="margin-top: 40px; font-size: 10px; color: #94a3b8; text-align: center;">
          Generated by Chronos Platform • ${new Date().toLocaleString()}
        </div>
      </div>
    `;

    // Create a temporary container
    const container = document.createElement('div');
    container.innerHTML = htmlContent;
    document.body.appendChild(container);

    const opt = {
      margin:       0.5,
      filename:     `Chronos_Plain_Report_${ticker}_${new Date().getTime()}.pdf`,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true },
      jsPDF:        { unit: 'in', format: 'a4', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(container).save().then(() => {
      document.body.removeChild(container);
    }).catch(err => {
      console.error("PDF Generation Error", err);
      document.body.removeChild(container);
    });
  };
  if (!results) return null;
  const { summary, risk_metrics: risk, trade_statistics: trades } = results;
  const isProfit = summary.total_return_percent >= 0;
  return (
    <div>
      {" "}
      <div className="flex items-center justify-between mb-4 px-1">
        {" "}
        <h2 className="text-lg font-bold text-slate-900 dark:text-zinc-50 ">
          Performance Summary
        </h2>{" "}
        <span className="text-xs font-medium px-2 py-1 bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-400 rounded-md">
          {" "}
          {results.strategy.toUpperCase()} • {results.ticker}{" "}
        </span>{" "}
      </div>{" "}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
        {" "}
        <StatCard
          label="Total Return" icon={Activity}
          value={fmt(summary.total_return_percent, "%")}
          subtext={`Final: ${region.currency}${fmt(summary.final_value)}`}
          negative={!isProfit}
          highlight={true}
        />{" "}
        <StatCard
          label="Annualized" icon={TrendingUp}
          value={fmt(summary.annualized_return_percent, "%")}
        />{" "}
        <StatCard
          label="Sharpe Ratio" icon={BarChart2}
          value={fmt(risk.sharpe_ratio)}
          subtext={`Vol: ${fmt(risk.volatility_percent, "%")}`}
        />{" "}
        <StatCard
          label="Max Drawdown" icon={TrendingDown}
          value={fmt(risk.max_drawdown_percent, "%")}
          negative={true}
        />{" "}
        <StatCard
          label="Win Rate" icon={Crosshair}
          value={fmt(trades.win_rate_percent, "%")}
          subtext={`${trades.total_trades} total trades`}
        />{" "}
      </div>{" "}
      <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
        {" "}
        <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl p-4 shadow-sm flex justify-between items-center">
          {" "}
          <span className="text-sm font-medium text-slate-600 dark:text-zinc-400 ">
            Benchmark (Buy & Hold)
          </span>{" "}
          <span className="text-sm font-bold text-slate-900 dark:text-zinc-50 ">
            {fmt(summary.benchmark_return_percent, "%")}
          </span>{" "}
        </div>{" "}
        <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl p-4 shadow-sm flex justify-between items-center">
          {" "}
          <span className="text-sm font-medium text-slate-600 dark:text-zinc-400 ">
            Strategy vs Benchmark
          </span>{" "}
          <span
            className={`text-sm font-bold ${summary.strategy_vs_benchmark >= 0 ? "text-emerald-600 dark:text-emerald-400" : "text-red-600 dark:text-red-400"}`}
          >
            {" "}
            {fmt(summary.strategy_vs_benchmark, "%")}{" "}
          </span>{" "}
        </div>{" "}
      </div>{" "}

      <div className="mt-6 flex justify-end">
        <button 
          onClick={handleDownloadReport}
          className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded-lg shadow-sm transition-colors text-sm cursor-pointer"
        >
          <Download size={16} />
          Generate Report
        </button>
      </div>
    </div>
  );
}
