import React, { useContext } from "react";
import { useRegion } from "../RegionContext";
import { TrendingUp, TrendingDown, Activity, Percent, Crosshair, BarChart2, Download } from 'lucide-react';

function fmt(n, suffix = "") {
  if (n === null || n === undefined) return "—";
  return `${Number(n).toLocaleString(undefined, { maximumFractionDigits: 2 })}${suffix}`;
}

function StatCard({
  label,
  value,
  subtext = null,
  highlight = false,
  negative = false,
  icon: Icon
}) {
  return (
    <div
      className={`p-5 rounded-xl border transition-all hover:-translate-y-1 hover:shadow-md ${highlight ? "bg-indigo-50 dark:bg-indigo-500/20 border-indigo-100 dark:border-indigo-500/30 " : "bg-white dark:bg-zinc-900 border-slate-200 dark:border-zinc-800 "} shadow-sm flex flex-col`}
    >
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs font-semibold text-slate-500 dark:text-zinc-400 uppercase tracking-wider">
          {label}
        </span>
        {Icon && <Icon className={`w-4 h-4 ${highlight ? 'text-indigo-500' : 'text-slate-400 dark:text-zinc-500'}`} />}
      </div>
      <div className="flex items-baseline gap-2">
        <span
          className={`text-2xl font-bold tracking-tight ${negative ? "text-red-600 dark:text-red-400" : "text-slate-900 dark:text-zinc-50 "}`}
        >
          {value}
        </span>
      </div>
      {subtext && (
        <span className="text-xs font-medium text-slate-400 dark:text-zinc-500 mt-1">{subtext}</span>
      )}
    </div>
  );
}
export default function ResultsTable({ results }) {
  const { region } = useRegion();

  const handleDownloadReport = () => {
    if (!results) return;
    const { summary, risk_metrics: risk, trade_statistics: trades } = results;
    
    let reportContent = `=======================================
CHRONOS QUANTITATIVE BACKTEST REPORT
=======================================

--- SUMMARY ---
Total Return: ${fmt(summary.total_return_percent, "%")}
Annualized Return: ${fmt(summary.annualized_return_percent, "%")}
Initial Capital: ${region.currency}${fmt(summary.initial_capital)}
Final Value: ${region.currency}${fmt(summary.final_value)}

--- RISK METRICS ---
Sharpe Ratio: ${fmt(risk.sharpe_ratio)}
Volatility: ${fmt(risk.volatility_percent, "%")}
Max Drawdown: ${fmt(risk.max_drawdown_percent, "%")}

--- TRADE STATISTICS ---
Win Rate: ${fmt(trades.win_rate_percent, "%")}
Total Trades: ${trades.total_trades}

--- BENCHMARK ---
Benchmark (Buy & Hold): ${fmt(summary.benchmark_return_percent, "%")}
Strategy vs Benchmark: ${fmt(summary.strategy_vs_benchmark, "%")}

Generated by Chronos Platform.`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Chronos_Report_${new Date().getTime()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };
  if (!results) return null;
  const { summary, risk_metrics: risk, trade_statistics: trades } = results;
  const isProfit = summary.total_return_percent >= 0;
  return (
    <div>
      {" "}
      <div className="flex items-center justify-between mb-4 px-1">
        {" "}
        <h2 className="text-lg font-bold text-slate-900 dark:text-zinc-50 ">
          Performance Summary
        </h2>{" "}
        <span className="text-xs font-medium px-2 py-1 bg-slate-100 dark:bg-zinc-800 text-slate-600 dark:text-zinc-400 rounded-md">
          {" "}
          {results.strategy.toUpperCase()} • {results.ticker}{" "}
        </span>{" "}
      </div>{" "}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
        {" "}
        <StatCard
          label="Total Return" icon={Activity}
          value={fmt(summary.total_return_percent, "%")}
          subtext={`Final: ${region.currency}${fmt(summary.final_value)}`}
          negative={!isProfit}
          highlight={true}
        />{" "}
        <StatCard
          label="Annualized" icon={TrendingUp}
          value={fmt(summary.annualized_return_percent, "%")}
        />{" "}
        <StatCard
          label="Sharpe Ratio" icon={BarChart2}
          value={fmt(risk.sharpe_ratio)}
          subtext={`Vol: ${fmt(risk.volatility_percent, "%")}`}
        />{" "}
        <StatCard
          label="Max Drawdown" icon={TrendingDown}
          value={fmt(risk.max_drawdown_percent, "%")}
          negative={true}
        />{" "}
        <StatCard
          label="Win Rate" icon={Crosshair}
          value={fmt(trades.win_rate_percent, "%")}
          subtext={`${trades.total_trades} total trades`}
        />{" "}
      </div>{" "}
      <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
        {" "}
        <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl p-4 shadow-sm flex justify-between items-center">
          {" "}
          <span className="text-sm font-medium text-slate-600 dark:text-zinc-400 ">
            Benchmark (Buy & Hold)
          </span>{" "}
          <span className="text-sm font-bold text-slate-900 dark:text-zinc-50 ">
            {fmt(summary.benchmark_return_percent, "%")}
          </span>{" "}
        </div>{" "}
        <div className="bg-white dark:bg-zinc-900 border border-slate-200 dark:border-zinc-800 rounded-xl p-4 shadow-sm flex justify-between items-center">
          {" "}
          <span className="text-sm font-medium text-slate-600 dark:text-zinc-400 ">
            Strategy vs Benchmark
          </span>{" "}
          <span
            className={`text-sm font-bold ${summary.strategy_vs_benchmark >= 0 ? "text-emerald-600 dark:text-emerald-400" : "text-red-600 dark:text-red-400"}`}
          >
            {" "}
            {fmt(summary.strategy_vs_benchmark, "%")}{" "}
          </span>{" "}
        </div>{" "}
      </div>{" "}
    </div>
  );
}
